name: music_mobile_app
description: "A Music Playlist Application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  just_audio: ^0.10.5
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true